blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://wordpress.org/support/plugin/attachment-taxonomies/
    about: Ask for help in the Attachment Taxonomies support forum.
