name: Deploy to WordPress.org

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Debug mode (run without publishing).'
        default: false

jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event.inputs.dry-run }}
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: attachment-taxonomies

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip