name: PHP Unit Testing

on:
  push:
    branches:
      - main
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'pnpm-lock.yaml'
      - 'phpunit.xml.dist'
      - 'tests/phpunit/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - main
      - 'feature/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test.yml'
      - '**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'pnpm-lock.yaml'
      - 'phpunit.xml.dist'
      - 'tests/phpunit/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  php-test:
    name: PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }} - ${{ matrix.multisite && 'Multisite' || 'Single site' }}${{ matrix.experimental && ' (experimental)' || '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php:
        - '7.2'
        - '7.3'
        - '7.4'
        - '8.0'
        - '8.1'
        - '8.2'
        wordpress: [ 'latest' ]
        multisite: [ false, true ]
        experimental: [false]
        include:
          - php: '7.0'
            wordpress: '6.1'
            multisite: false
          - php: '7.0'
            wordpress: '6.1'
            multisite: true
          - php: '8.0'
            wordpress: '6.1'
            multisite: false
          - php: '8.0'
            wordpress: '6.1'
            multisite: true
          - php: '8.2'
            wordpress: 'trunk'
            multisite: false
            experimental: true
          - php: '8.2'
            wordpress: 'trunk'
            multisite: true
            experimental: true
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}
      WP_ENV_CORE: ${{ matrix.wordpress == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wordpress ) }}
    continue-on-error: ${{ matrix.experimental == true }}
    steps:
      - uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm wp-env start

      - name: Running ${{ matrix.multisite && 'multisite' || 'single site' }} unit tests
        run: pnpm test-php${{ matrix.multisite && '-multisite' || '' }}
