name: Plugin Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: wordpress/plugin-check-action@10857da14b6c2246d15402b3e69f777edcf8c12e # 1.1.9
        with:
          wp-version: 'latest'
          # Exclude file_type because of the dev files present in the repository.
          # Exclude i18n_usage temporarily because of https://github.com/WordPress/plugin-check/issues/713.
          exclude-checks: |
            file_type
            i18n_usage
          exclude-directories: |
            .github
            tests