name: Update assets on WordPress.org

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: attachment-taxonomies
          IGNORE_OTHER_FILES: true